create table `nhl_jeffery_tree`.`goal_entropy_full` select A.NodeId as NodeId, A.CurrentValue as Home, B.CurrentValue as Away, A.CurrentValue/(A.CurrentValue+B.CurrentValue)*LOG(2,(A.CurrentValue+B.CurrentValue)/A.CurrentValue)+B.CurrentValue/(A.CurrentValue+B.CurrentValue)*LOG(2,(A.CurrentValue+B.CurrentValue)/B.CurrentValue) as Entropy from nhl_fast_value_iteration_full.probability_next_home_goal as A, nhl_fast_value_iteration_full.probability_next_away_goal as B where A.NodeId=B.NodeId;

create table `nhl_jeffery_tree`.`penalty_entropy_full` select A.NodeId as NodeId, A.CurrentValue as Home, B.CurrentValue as Away, A.CurrentValue/(A.CurrentValue+B.CurrentValue)*LOG(2,(A.CurrentValue+B.CurrentValue)/A.CurrentValue)+B.CurrentValue/(A.CurrentValue+B.CurrentValue)*LOG(2,(A.CurrentValue+B.CurrentValue)/B.CurrentValue) as Entropy from nhl_fast_value_iteration_full.probability_next_home_penalty as A, nhl_fast_value_iteration_full.probability_next_away_penalty as B where A.NodeId=B.NodeId;

create table `nhl_jeffery_tree`.`goal_entropy_penalty` select A.NodeId as NodeId, A.CurrentValue as Home, B.CurrentValue as Away, A.CurrentValue/(A.CurrentValue+B.CurrentValue)*LOG(2,(A.CurrentValue+B.CurrentValue)/A.CurrentValue)+B.CurrentValue/(A.CurrentValue+B.CurrentValue)*LOG(2,(A.CurrentValue+B.CurrentValue)/B.CurrentValue) as Entropy from nhl_fast_value_iteration_penalty.probability_next_home_goal as A, nhl_fast_value_iteration_penalty.probability_next_away_goal as B where A.NodeId=B.NodeId;

create table `nhl_jeffery_tree`.`penalty_entropy_penalty` select A.NodeId as NodeId, A.CurrentValue as Home, B.CurrentValue as Away, A.CurrentValue/(A.CurrentValue+B.CurrentValue)*LOG(2,(A.CurrentValue+B.CurrentValue)/A.CurrentValue)+B.CurrentValue/(A.CurrentValue+B.CurrentValue)*LOG(2,(A.CurrentValue+B.CurrentValue)/B.CurrentValue) as Entropy from nhl_fast_value_iteration_penalty.probability_next_home_penalty as A, nhl_fast_value_iteration_penalty.probability_next_away_penalty as B where A.NodeId=B.NodeId;

create table `nhl_jeffery_tree`.`goal_entropy_local` select A.NodeId as NodeId, A.CurrentValue as Home, B.CurrentValue as Away, A.CurrentValue/(A.CurrentValue+B.CurrentValue)*LOG(2,(A.CurrentValue+B.CurrentValue)/A.CurrentValue)+B.CurrentValue/(A.CurrentValue+B.CurrentValue)*LOG(2,(A.CurrentValue+B.CurrentValue)/B.CurrentValue) as Entropy from nhl_fast_value_iteration_local.probability_next_home_goal as A, nhl_fast_value_iteration_local.probability_next_away_goal as B where A.NodeId=B.NodeId;

create table `nhl_jeffery_tree`.`penalty_entropy_local` select A.NodeId as NodeId, A.CurrentValue as Home, B.CurrentValue as Away, A.CurrentValue/(A.CurrentValue+B.CurrentValue)*LOG(2,(A.CurrentValue+B.CurrentValue)/A.CurrentValue)+B.CurrentValue/(A.CurrentValue+B.CurrentValue)*LOG(2,(A.CurrentValue+B.CurrentValue)/B.CurrentValue) as Entropy from nhl_fast_value_iteration_local.probability_next_home_penalty as A, nhl_fast_value_iteration_local.probability_next_away_penalty as B where A.NodeId=B.NodeId;
